### PR TITLE
Arrangement

### PR DESCRIPTION
**Pull request by Genetik57**
*Revised file for better organization of consoles

-Genetik57

### CODE REVIEW

**Comment by nadenislamarre** [comment]
thanks.
i've to reread it more deeply to be sure.

**Comment by Genetik57** [comment]
Hello,

No problem everything is there

**Comment by Genetik57** [comment]
Updated !

**Comment by Genetik57** [comment]
File updated with the latest changes commited by @nadenislamarre

**Comment by nadenislamarre** [comment]
there is a problem with this pr : it includes all my previous changes, not only your changes.

**Comment by Genetik57** [comment]
The goal is to improve your file (New organization)

**Comment by nadenislamarre** [comment]
i get the goal. but the pr is not correct.
if you go in "files modified", you can read that it contains more than just your modifications.
you may have to rebase it.

**Comment by Genetik57** [comment]
Yet I relied on the last commit of this morning, I only reclassified the emulators

**Comment by nadenislamarre** [comment]
not on discord ?

**Pull request closed without merging**
