### PR TITLE
Updated libretroConfig.py 

### PR DESCRIPTION
**Pull request by Genetik57**

### CODE REVIEW

**Comment by nadenislamarre** [comment]
Thanks.
What is the aim of these changes ?
Why do you modify "systemNoRewind" ?

**Comment by Genetik57** [comment]
https://gitlab.com/recalbox/recalbox-configgen/commit/81f086e4869bf6d76a98b6d7c2d8d443c434e950 and https://gitlab.com/recalbox/recalbox-configgen/commit/294e9890372e57329bd1d6ba51c447034a504ac0

**Comment by nadenislamarre** [comment]
i've not understood the aim of theses changes. do you know ?
for the systemNoRewind, i don't agree about the change. a girl review this point last week on the forum and fixed this line. please update the commit the the value it was updated last week.

**Comment by nadenislamarre** [comment]
but what this code is supposed to do ?

**Comment by Genetik57** [comment]
For the time being, I'm just transferring the official changes. If for you it is Ok made the merge otherwise cancel this merge. Do you understand ?

**Pull request closed without merging**
